- name: Deploy Order Tracking Frontend
    run: |
      echo "Deploying TRACKING Frontend PROD"
      cd /home/ubuntu/projects/thecargo/order-tracking
      git fetch origin
      git reset --hard origin/master
      npm install
      npm run build
